### ISSUE TITLE
`publish` calls `spawnAsync.default`

### ISSUE THREAD

**Issue by soulofmischief** [ffflorian/publish-flat#94]
`publish` calls `spawnAsync.default` instead of `spawnAsync` in the compiled code, resulting in a `TypeError`.

There are a few ways to handle the problem: 

* fix the issue upstream in `@expo/spawn-async` so that the proper `default` property is added to `module.exports`

* work around the issue by using `require` instead of `import` for `spawnAsync`.

One is more correct, one is easier. I'll leave it up to you.

**Comment by ffflorian** [comment]
Hi @soulofmischief, thanks for the report. Some time ago I opened https://github.com/expo/spawn-async/issues/18 it seemed like setting `allowSyntheticDefaultImports` in `tsconfig.json` worked. Seems like it didn't really work :smiley:
